# Generated by Django 3.1.6 on 2021-06-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210624_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.app'),
        ),
    ]
