# Generated by Django 3.2.5 on 2021-08-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_user_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_from', models.CharField(max_length=200)),
                ('username_to', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('body', models.TextField()),
                ('sending_datetime', models.DateTimeField()),
                ('received', models.BooleanField()),
                ('readed', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='database_code',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
