# Generated by Django 3.2.5 on 2021-08-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210805_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unreaded_mail',
            field=models.CharField(default='()', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='unreceved_mail',
            field=models.CharField(default='()', max_length=200),
        ),
    ]
