# Generated by Django 3.2.5 on 2021-08-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210805_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unreaded_mail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unreceved_mail',
        ),
        migrations.AddField(
            model_name='profile',
            name='new_mail',
            field=models.CharField(default='()', max_length=200),
        ),
    ]
