# Generated by Django 3.2.5 on 2021-08-05 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20210805_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='username_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='username_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='username_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='new_mail',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
