# Generated by Django 3.2.5 on 2021-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210805_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='new_mail',
            field=models.BooleanField(default=True),
        ),
    ]
