# Generated by Django 3.2.5 on 2021-08-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210814_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='home_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
