# Generated by Django 3.2.5 on 2021-08-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210818_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storage_file_pk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='users_files/'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(default='New Folder', max_length=200),
        ),
    ]
