# Generated by Django 3.2.5 on 2021-09-23 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_auto_20210923_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='username_to',
        ),
        migrations.AlterField(
            model_name='mail',
            name='username_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
