# Generated by Django 3.2.5 on 2021-09-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210923_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new_mail_inbox',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='new_mail_outbox',
        ),
    ]
