# Generated by Django 3.2.5 on 2021-09-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_mail_bcc_receiver_readed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='readed',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='received',
        ),
    ]
