# Generated by Django 3.2.5 on 2021-09-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210923_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_bcc_receiver',
            name='DT',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mail_cc_receiver',
            name='DT',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
