# Generated by Django 3.2.5 on 2021-09-24 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210923_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_bcc_receiver',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 18, 22, 17, 338297)),
        ),
        migrations.AddField(
            model_name='mail_cc_receiver',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 18, 22, 17, 337859)),
        ),
    ]
