# Generated by Django 3.1.6 on 2021-06-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerController', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artical',
        ),
    ]
