# Generated by Django 3.2.5 on 2021-07-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('INSPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packedproductpackingmaterial',
            old_name='quantity_in_one',
            new_name='count',
        ),
    ]
