# Generated by Django 3.2.5 on 2021-08-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSPP', '0002_rename_quantity_in_one_packedproductpackingmaterial_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='packedproduct',
            name='unpacked_product_quantity_in_one',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='packedproductpackingmaterial',
            name='count',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='packingmaterial',
            name='loq_quantity',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='packingmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='packingmaterialinput',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packingmaterialinput',
            name='quantity',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='packingmaterialoutput',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packingmaterialoutput',
            name='quantity',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='density',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='loq_quantity',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='m_type',
            field=models.CharField(choices=[('solid', 'solid'), ('liquid', 'liquid'), ('gas', 'gas')], max_length=200),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='rawmaterialsinput',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialsinput',
            name='quantity',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='rawmaterialsoutput',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialsoutput',
            name='quantity',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='unpackedproduct',
            name='material_type',
            field=models.CharField(choices=[('solid', 'solid'), ('liquid', 'liquid'), ('gas', 'gas')], max_length=200),
        ),
        migrations.AlterField(
            model_name='unpackedproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='unpackedproductrawmaterial',
            name='percent',
            field=models.DecimalField(decimal_places=90, default=0, max_digits=100),
        ),
    ]
